@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class AbstractTimeUnit {
   getMapping(): 
   getCases(): 
}
class AbstractUnit {
   __construct(value): 
   defaultPrecision: 
   defaultRoundingMode: 
   value: 
   __toString(): 
   getMapping(): 
   convert(targetUnitClass): 
   expandScientificNotation(number): 
   create(value, unitType): 
   fixTrailingZeros(number): 
   round(precision, mode): 
   getValue(): 
   normalize(): 
   format(precision, mode): 
   getChoices(): 
}
class BackedEnum {
   value: 
   from(value): 
   tryFrom(value): 
}
class Day {
   getFactor(): 
   getSymbol(): 
   getUnitType(): 
}
class Hour {
   getFactor(): 
   getSymbol(): 
   getUnitType(): 
}
class Microsecond {
   getFactor(): 
   getSymbol(): 
   getUnitType(): 
}
class Millisecond {
   getFactor(): 
   getSymbol(): 
   getUnitType(): 
}
class Minute {
   getFactor(): 
   getSymbol(): 
   getUnitType(): 
}
class Month {
   getFactor(): 
   getSymbol(): 
   getUnitType(): 
}
class Nanosecond {
   getFactor(): 
   getSymbol(): 
   getUnitType(): 
}
class Picosecond {
   getFactor(): 
   getSymbol(): 
   getUnitType(): 
}
class Second {
   getFactor(): 
   getSymbol(): 
   getUnitType(): 
}
class StringBackedEnum {
   value: 
   from(value): 
   tryFrom(value): 
}
class TimeUnitInterface
class TimeUnitType {
   fromString(unit): 
   normalize(unit): 
}
class UnitEnum {
   name: 
   cases(): 
}
class UnitInterface {
   getMapping(): 
   convert(targetUnitClass): 
   create(value, unitType): 
   getFactor(): 
   getSymbol(): 
   getCases(): 
   round(precision, mode): 
   getUnitType(): 
   getValue(): 
   normalize(): 
   format(precision, mode): 
   getChoices(): 
}
class Week {
   getFactor(): 
   getSymbol(): 
   getUnitType(): 
}
class Year {
   getFactor(): 
   getSymbol(): 
   getUnitType(): 
}

AbstractTimeUnit   -[#000082,plain]-^  AbstractUnit      
AbstractTimeUnit   -[#008200,dashed]-^  TimeUnitInterface 
AbstractUnit       -[#008200,dashed]-^  UnitInterface     
BackedEnum         -[#008200,plain]-^  UnitEnum          
Day                -[#000082,plain]-^  AbstractTimeUnit  
Hour               -[#000082,plain]-^  AbstractTimeUnit  
Microsecond        -[#000082,plain]-^  AbstractTimeUnit  
Millisecond        -[#000082,plain]-^  AbstractTimeUnit  
Minute             -[#000082,plain]-^  AbstractTimeUnit  
Month              -[#000082,plain]-^  AbstractTimeUnit  
Nanosecond         -[#000082,plain]-^  AbstractTimeUnit  
Picosecond         -[#000082,plain]-^  AbstractTimeUnit  
Second             -[#000082,plain]-^  AbstractTimeUnit  
StringBackedEnum   -[#008200,plain]-^  BackedEnum        
TimeUnitInterface  -[#008200,plain]-^  UnitInterface     
TimeUnitType       -[#008200,dashed]-^  BackedEnum        
Week               -[#000082,plain]-^  AbstractTimeUnit  
Year               -[#000082,plain]-^  AbstractTimeUnit  
@enduml
